#!/usr/bin/env bash

## Install ansible and other core utilities
sudo apt update
sudo apt install -y curl git software-properties-common ansible

# ansible-playbook local.yml --ask-vault-password --ask-become-pass
