- name: Check for private key
  become_user: matts
  stat:
    path: ~/.ssh/id_rsa
  register: pkey
  tags:
    - config
    - ssh
  
- name: Ensure ~/.ssh directory exists
  become_user: matts
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
  when: pkey.stat.exists == False
  tags:
    - config
    - ssh

- name: Copy SSH public key to host
  become_user: matts
  ansible.builtin.copy:
    src: vault/id_rsa.pub
    dest: ~/.ssh
    decrypt: no
  when: pkey.stat.exists == False
  tags:
    - config
    - ssh

- name: Copy SSH private key to host
  become_user: matts
  ansible.builtin.copy:
    src: vault/id_rsa
    dest: ~/.ssh
    mode: '0600'
    decrypt: yes
  when: pkey.stat.exists == False
  tags:
    - config
    - ssh
    - encrypted
    - vault
